# Generated by Django 4.0.2 on 2022-03-11 10:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nse_comp', models.CharField(default='', max_length=200)),
                ('s_d', models.DateField(blank=True, null=True)),
                ('e_d', models.DateField(blank=True, null=True)),
                ('open_img', models.ImageField(default='', max_length=250, upload_to='media/')),
                ('Change_img', models.ImageField(default='', max_length=250, upload_to='media/')),
                ('Data_img', models.ImageField(default='', max_length=250, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
