# Generated by Django 2.1.5 on 2022-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('msg', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='nsedata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
